### ISSUE TITLE
Update details of the README

### ISSUE THREAD

**Issue by kristenwomack** [Azure-Samples/contoso-chat-csharp-prompty#36]
Update README file so it matches the completeness of the [OpenAI Python PF README](https://github.com/Azure-Samples/summarization-openai-python-promptflow)

- [x] do we want to add a list of regions where this template will work? https://aka.ms/semanticsearchavailability
- [x] if there is a reason we ask for the region 2x, we should document this (noted [here](https://github.com/Azure-Samples/contoso-chat-csharp-prompty/issues/38#issuecomment-2108645171))
- [ ] remove `az` deployment instructions (once the azd PR is approved and merged)
- [ ] update specifics about regions to make certain it's as clear as possible

**Comment by kristenwomack** [comment]
@cassiebreviu - reopening this, @PabloNunes is still working on this with feedback from me and @anfibiacreativa.

**Comment by kristenwomack** [comment]
This template does ask for region 2x and has been updated in the readme. 
https://github.com/Azure-Samples/contoso-chat-csharp-prompty/pull/42
https://github.com/Azure-Samples/contoso-chat-csharp-prompty/issues/38#issuecomment-2108764640

**Comment by kristenwomack** [comment]
@PabloNunes - will you add the tasks you're working on to update the README and push your latest changes? @gkulin and I are working and don't want to duplicate efforts. 

cc: @anfibiacreativa

**Comment by PabloNunes** [comment]
Updated the docs, take a look,.
#50
