### ISSUE TITLE
Test Template

### ISSUE THREAD

**Issue by kristenwomack** [Azure-Samples/contoso-chat-csharp-prompty#51]
- [ ] Testing works following the Readme, Codespaces is the priority
- [ ] Make sure azd works in Codespaces (flag to fix if not)
- [ ] We have verification step in README after the resources are deployed, there is a description of what the customer needs to do next
- [ ] Ensure managed identity is implemented and working
- [ ] If local doesn't work, we need a note in the README (make this explicit)

Nice to have (but document if not working)
- [ ] runs local

Must have two testers approval, minimum.

**Comment by jmatthiesen** [comment]
I can't add myself as an assignee, but FYI that I'm looking at this issue now.

**Comment by jmatthiesen** [comment]
In devcontainer.json, we should include the C# dev kit (VS Code extension: ms-dotnettools.csdevkit) to improve the C# developer experience. This doesn't add much, if any, to the CodeSpaces provisioning time and provides a more familiar experience for .NET devs.

**Comment by kristenwomack** [comment]
I'm getting this error and I'm not sure what it means. 
![image](https://github.com/Azure-Samples/contoso-chat-csharp-prompty/assets/5034778/2833404e-f56a-462b-a1b6-ab406649f841)

**Comment by jmatthiesen** [comment]
@kristenwomack What steps did you follow when you got that error? Pablo just submitted a fix for the Codespaces buttons in the readme, did you happen to use one of those?

**Comment by jmatthiesen** [comment]
Validated:
* AZD worked in Codespaces
* The testing flow in Codespaces worked for me (and I updated missing steps)
* Managed Identity works

Next up, I'm making a quick validation pass locally to ensure the steps work as written. I have verified local in the past, but not by following step-by step instructions in the README.
